
# Sample requirements.yaml

# collections:
  # Install a collection fr
  #- name: geerlingguy.php_
  #  version: 0.9.3
  #  source: https://galaxy

collections:
  - name: community.network
    version: 5.0.2
  - name: community.general
    version: 8.2.0