---

 - name: configure tacac settings
   hosts: AzureWLC
   gather_facts: false

   tasks:

     - name: show current tacacs settings
       cisco.ios.ios_command:
         commands:
           - show running-config | section tacacs
       register: output

     - name: Display sh tacacs result
       debug:
         var: output.stdout_lines

     - name: Deploy tacacs settings to GRDC-ISEPOL01a-TACAC
       cisco.ios.ios_config:
         lines:        
           - address ipv4 10.254.199.201
           - key 7 Some Key Value 
         parents: tacacs server GRDC-ISEPOL01a-TACACS

     - name: Deploy tacacs settings to SBDC-ISEPOL01a-TACACS
       cisco.ios.ios_config:
         lines:        
           - address ipv4 10.255.199.201
           - key 7 Some Key Value
         parents: tacacs server SBDC-ISEPOL01a-TACACS
    



   
     
     
     
     
     
     
     
   
   