---

 - name: configure logging settings
   hosts: 
   gather_facts: false

   tasks:

     - name: show current logging settings
       cisco.ios.ios_command:
         commands:
           - show running-config | section logging
       register: output

     - name: Display sh logging result
       debug:
         var: output.stdout_lines

     - name: Deploy logging settings
       cisco.ios.ios_config:
         lines:        
           - logging trap debugging
           - logging host 10.255.225.2 transport udp port 514 session-id hostname sequence-num-session
           - logging host 10.255.224.63 transport udp port 514 session-id hostname sequence-num-session
           - logging host 10.255.199.100 transport udp port 514 session-id hostname sequence-num-session
           - logging host 172.20.0.11 transport udp port 514 session-id hostname sequence-num-session
           - logging buffered 40960

     - name: Save running to startup when modified
       cisco.ios.ios_config:
        save_when: modified

     - name: diff the running-config against a provided config
       cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('intended-config-logging.txt','startup') }}"