---

- name: ios_test
  hosts: all
  gather_facts: false
    
  tasks:
    - name: Run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
      register: result

    - name: Display result to terminal window
      debug:
        var: result.stdout_lines
