---

- name: Configure BUWLC
  hosts: BUWLC
  gather_facts: false
  
  tasks:
  - name: Configure configuration
    community.network.aireos_config:
      lines: 
        - wlan apgroup add IN999 Ansible,IN

   
   
   
   

   

   
   
   
   

   
