---

  - name: set hostname
    hosts: L3_Switches
    gather_facts: false

    tasks:

      - name: gather current hostname
        cisco.ios.ios_hostname:
          state: gathered

      - name: Apply the provided configuration
        cisco.ios.ios_hostname:
          config:
            hostname: "{{ plantid }}{{ dash }}{{ core_mdf_id }}{{ nn }}"
          state: merged
