---
- name: SNMP ro/rw string configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Ensure that the desired snmp strings are present
      cisco.ios.ios_config:
        commands:
          - snmp-server location {{ physloc }}
         # - snmp-server community {{ snmp_var1 }} RO
          - snmp-server community {{ snmp_var2 }} RO
          - snmp-server contact {{ email_contact }}