---

- name: WLC.yaml
  hosts: WLC
  gather_facts: false
  connection:  ssh

  tasks:

    - name: Run Show Commands and Output
      community.network.aireos_command:
         commands='show interface summary'
      register: out

    - debug: var=out.stdout_lines

    - copy:
        content: "{{ out.stdout_lines }}"
        dest: /tmp/WLC_yaml_out.txt
        mode: 0640

    - name: Run Show AP Summary
      community.network.aireos_command:
         commands='show ap summary'
      register: out1

    - debug: var=out1.stdout_lines

    - copy:
        content: "{{ out1.stdout_lines }}"
        dest: /tmp/WLC_yaml_out1.txt
        mode: 0640
