---

 - name: set tacacs
   hosts: AzureWLC
   gather_facts: false

   tasks:

     - name: sh current tacacs swttings
       ios_command:
         commands:
           show run | i tacacs
       register: output

     - name: Display sh tacacs result
       debug:
         var: output.stdout_lines

     - name: Create tacacs server group(s)
       cisco.ios.ios_config:
         lines:
           tacacs server SBDC-ISEPOL01a-TACACS
           tacacs server GRDC-ISEPOL01a-TACACS

     - name: Deploy tacacs settings to SBDC-ISEPOL01a-TACACS
       cisco.ios.ios_config:
         lines:        
           tacacs server address ipv4 10.255.199.201
           tacacs key 7 10602530241B0612055273247119611929
         parents:
           tacacs server SBDC-ISEPOL01a-TACACS
      
      - name: Deploy tacacs settings to SBDC-ISEPOL01a-TACACS
        cisco.ios.ios_config:
          lines:        
            tacacs server address ipv4 10.254.199.201
            tacacs key 7 10602530241B0612055273247119611929
          parents:
            tacacs server GRDC-ISEPOL01a-TACACS
               

      
