---

 - name: set aaa
   hosts: AzureWLC
   gather_facts: false

   tasks:

     - name: sh current aaa swttings
       ios_command:
         commands:
           show run | i aaa
       register: output

     - name: Display sh aaa result
       debug:
         var: output.stdout_lines

     - name: Set aaa values
       cisco.ios.ios_config:
          commands:
            aaa authentication login default local-case

      
