---

 - name: set tacacs
   hosts: AzureWLC
   gather_facts: false

   tasks:

     - name: sh current tacacs swttings
       ios_command:
         commands:
           show run | i tacacs
       register: output

     - name: Display sh tacacs result
       debug:
         var: output.stdout_lines

   tasks:  

     - name: Create tacacs server SBDC-ISEPOL01a-TACACS
       cisco.ios.ios_config:
         lines:
           tacacs server SBDC-ISEPOL01a-TACACS

      - name: Create tacacs server GRDC-ISEPOL01a-TACACS
        cisco.ios.ios_config:
          lines:
            tacacs server GRDC-ISEPOL01a-TACACS
    



   
     
     
     
     
     
     
     
   
   