---
- name: SNMP ro/rw string configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Ensure that the desired snmp strings are present
      cisco.ios.ios_config:
        commands:
          - snmp-server location {{ physloc }}
          - snmp-server community lippert RO
          - snmp-server community xT29pyZ*#X6SkAmBw* RO
          - snmp-server contact itnoc@lci1.com