---

- name: WLC.yaml
  hosts: all
  gather_facts: false
  
  tasks:

    - name: Run show sysinfo on remote devices
      community.network.aireos_command:
        commands: show sysinfo
      register: bobbysue

    - debug: var=bobbysue.stdout_lines 

    - name: Run Show Commands and Output
      community.network.aireos_command:
        commands: show interface summary
      register: out

    - debug: var=out.stdout_lines

    - name: Run Show AP Summary
      community.network.aireos_command:
        commands: show ap summary
      register: out1

    - debug: var=out1.stdout_lines
